### PR TITLE
NVIDIA GPU performance optimizations, GPU example scripts, and gin convergence configs

### PR DESCRIPTION
**Pull request by SahilJain314**
These are the optimizations and other changes that we have been working on for GPU at NVIDIA. Summary of changes available in our shared doc.

### CODE REVIEW

**Review by hwchung27 — COMMENTED** [review]
This seems to be too big of a scope.

I think we should put it under contrib (I thought we agreed to do so in the last sync, no?) with a more general name like "t5x/contrib/gpu" because the changes seem relevant not just for t5.

For the changes in train.py and trainer.py, we should try to merge them to the core library so that you don't fork those.

**Comment by hwchung27** [comment]
Also the current format makes it hard to see what are copied and what changes are newly added. I am not too familiar with git but preserved copy history will make the review process much easier.

**Comment by sharathts** [comment]
@hwchung27 We did discuss contrib, but the consensus was to add changes to `t5x/examples/gpu_t5` since we aren't allowed to modify `t5x/examples/t5`.

Re: "For the changes in train.py and trainer.py, we should try to merge them to the core library so that you don't fork those."
These changes are already present in `t5x/train.py` and `t5x/trainer.py`, do you mean something else? Thanks! 

@SahilJain314 for viz

**Comment by hwchung27** [comment]
We discussed both options but I did not see the code back then. The scale of change seems to be too big to be "examples". But then it is hard to say because the diff information is not really there.

I think the most important thing is to set the diff so that we can properly review this, i.e. what are new changes and what are just copied over.

**Comment by SahilJain314** [comment]
[d.txt](https://github.com/google-research/t5x/files/10070391/d.txt)
I've attached the diff here.

**Comment by sharathts** [comment]
> what are new changes

the very first commit in the PR also shows the changes in `t5` which are now container in `gpu_t5`. Changes in `train.py` and `trainer.py` are also seen. https://github.com/google-research/t5x/pull/857/commits/7166457ef53349fd3f782401107913fb49f1ae4c

The rest are scripts to facilitate push button pre-training and finetuning.

**Pull request closed without merging**
